default: &default
  refresh_connections:
    class: RefreshConnectionJob
    cron: '* */2 * * * * Europe/Kiyv'
  # active_mailings:
  #   class: ActiveMailingsWorker
  #   cron: '*/10 * * * * * America/Phoenix'
  # scheduled_mailings:
  #   class: ScheduledMailingsWorker
  #   cron: '* * * * * America/Phoenix'

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default